# -*- coding: utf-8 -*-
"""BCI_Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j71YfReClce7HMzEIWha8PY26YcJn2cr
"""

# Step 1: Import necessary libraries
from google.colab import drive
import scipy.io

# Step 2: Mount your Google Drive
# This will prompt you for authorization. Follow the link, get the authorization code,
# paste it in the box, and press Enter.
print("Mounting Google Drive...")
drive.mount('/content/drive')
print("Drive mounted successfully!")

# Step 3: Define the path to your file
# IMPORTANT: This path assumes the file is directly in your "My Drive" folder.
# If you placed it in a subfolder, you must change the path accordingly.
# For example: '/content/drive/My Drive/BCI_Project/A01T.mat'
file_path = '/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat'

# Step 4: Load the .mat file
print(f"Loading data from: {file_path}")
try:
    mat_data = scipy.io.loadmat(file_path)
    print("File loaded successfully!")

    # Step 5: Print the loaded data to inspect its structure
    print("\n--- Structure of the loaded data ---")
    print(mat_data)

except FileNotFoundError:
    print(f"\nERROR: File not found at the specified path.")
    print("Please make sure the file_path variable is correct and the file is in your Google Drive.")

# --- Forensic Analysis: Layer 1 ---

# We know this line works and loads the file into a dictionary
mat_data = scipy.io.loadmat('/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat')

# Let's inspect the top layer
print("--- Layer 1: The Top Level Object ---")
print(f"Type of mat_data: {type(mat_data)}")
print(f"Keys in mat_data: {mat_data.keys()}")

# Now let's grab the object associated with the 'data' key and inspect it
print("\n--- Layer 2: The 'data' Object ---")
level2_object = mat_data['data']
print(f"Type of level2_object: {type(level2_object)}")
print(f"Shape of level2_object: {level2_object.shape}")

# --- Forensic Analysis: Layer 3 ---

# From the previous step, we have level2_object
level2_object = mat_data['data']

# We know its shape is (1, 9). Let's select the first subject's data.
# The data for the first subject is at index [0, 0].
level3_subject1_object = level2_object[0, 0]

# Now, let's inspect this single-subject object
print("\n--- Layer 3: The Object for Subject 1 ---")
print(f"Type of level3_subject1_object: {type(level3_subject1_object)}")

# This is the most important line: Let's look at the fields INSIDE this object.
# This should give us the familiar ['X', 'trial', 'y', ...] list.
print(f"\nFields inside Subject 1 object: \n{level3_subject1_object.dtype}")

import numpy as np
import scipy.io
from google.colab import drive

# --- Mount Drive and Load File (if needed, otherwise comment out) ---
# drive.mount('/content/drive')
# file_path = '/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat'
# mat_data = scipy.io.loadmat(file_path)

# --- The Final, Correct Extraction ---

# 1. Access the (1, 9) array containing all subjects' data
all_subjects_data = mat_data['data']

# 2. Select the data structure for the first subject (at index [0, 0])
subject1_data_structure = all_subjects_data[0, 0]

# 3. Extract the data from the fields of this structure
X = subject1_data_structure['X']
trial_starts = subject1_data_structure['trial']
y = subject1_data_structure['y']
fs = subject1_data_structure['fs']
class_labels = subject1_data_structure['classes']

# 4. Clean up the extracted data into a usable format
y = y.flatten()
sampling_freq = fs.item()
class_names = [label[0] for label in class_labels[0]]

# --- Print the shapes and info to verify ---
print("--- Data Extracted Successfully ---")
print(f"Shape of X (EEG signals): {X.shape}")
print(f"Shape of trial_starts (trial start samples): {trial_starts.shape}")
print(f"Shape of y (class labels): {y.shape}")
print(f"Sampling Frequency: {sampling_freq} Hz")
print(f"Class Names: {class_names}")
print(f"Unique Labels in y: {np.unique(y)}")

import scipy.io
mat_data = scipy.io.loadmat(file_path) # Assuming file_path is already defined

mat_data['data'].shape

# From the last step, we know mat_data['data'] is a (1, 9) array.
# Let's grab the object for the first subject, which is at index [0, 0].
subject_object = mat_data['data'][0, 0]

# Now, let's inspect the 'dtype' of this subject_object.
# This will tell us the names of the data fields inside it.
subject_object.dtype

# From the last step, we have subject_object
subject_object = mat_data['data'][0, 0]

# Now, let's access the container inside the 'X' field
x_container = subject_object['X']

# Let's inspect this container to see its type and shape
print(f"Type of x_container: {type(x_container)}")
print(f"Shape of x_container: {x_container.shape}")

import numpy as np
import scipy.io
from google.colab import drive

# --- Mount Drive and Load File (if needed) ---
# drive.mount('/content/drive')
# file_path = '/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat'
# mat_data = scipy.io.loadmat(file_path)


# --- The Final, Correct Extraction, Built Step-by-Step ---

# 1. Get the (1, 9) array of all subjects' data
all_subjects_data = mat_data['data']

# 2. Select the structured array for the first subject
subject_object = all_subjects_data[0, 0]

# 3. Access the (1, 1) container for each field and get the final data array from inside it at index [0, 0]
X = subject_object['X'][0, 0]
trial_starts = subject_object['trial'][0, 0]
y = subject_object['y'][0, 0]
fs = subject_object['fs'][0, 0]
class_labels = subject_object['classes'][0, 0]

# 4. Clean up the extracted data into a usable format
y = y.flatten()
sampling_freq = fs.item()
# The class names are also nested, this comprehension will extract the clean strings
class_names = [label[0] for label in class_labels]


# --- Print the shapes and info to verify ---
print("--- Data Extracted Successfully ---")
print(f"Shape of X (EEG signals): {X.shape}")
print(f"Shape of trial_starts (trial start samples): {trial_starts.shape}")
print(f"Shape of y (class labels): {y.shape}")
print(f"Sampling Frequency: {sampling_freq} Hz")
print(f"Class Names: {class_names}")
print(f"Unique Labels in y: {np.unique(y)}")

# From our previous steps, we have the subject_object
subject_object = mat_data['data'][0, 0]

# --- Let's inspect the 'trial' container ---
trial_container = subject_object['trial']
print(f"--- Inspecting 'trial' container ---")
print(f"Type of trial_container: {type(trial_container)}")
print(f"Shape of trial_container: {trial_container.shape}")
print(f"Content of trial_container: {trial_container}")

# --- Now let's inspect the 'y' container ---
y_container = subject_object['y']
print(f"\n--- Inspecting 'y' container ---")
print(f"Type of y_container: {type(y_container)}")
print(f"Shape of y_container: {y_container.shape}")
print(f"Content of y_container: {y_container}")

# --- Final Attempt with a Different Loading Method ---

# We load the file again, but with squeeze_me=True
mat_data_squeezed = scipy.io.loadmat(file_path, squeeze_me=True)

# Let's print the entire structure of this new object
# This will show us everything inside in a simplified view
print(mat_data_squeezed)

import numpy as np
import scipy.io
from google.colab import drive

# --- Mount Drive and Load File (if needed) ---
# drive.mount('/content/drive')
# file_path = '/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat'

# --- The Final, Correct Extraction ---

# 1. Load the data using the squeeze_me=True argument
mat_data_squeezed = scipy.io.loadmat(file_path, squeeze_me=True)

# 2. Access the array containing all subjects' data
all_subjects_data = mat_data_squeezed['data']

# 3. Select the data for a subject that has labels (e.g., the 4th subject at index 3)
subject_data = all_subjects_data[3] # Using Subject 4

# 4. Extract the data directly from the fields. No extra indexing needed!
X = subject_data['X']
trial_starts = subject_data['trial']
y = subject_data['y']
sampling_freq = subject_data['fs']
class_names = subject_data['classes']

# --- Print the shapes and info to verify ---
print("--- Data Extracted Successfully ---")
print(f"Shape of X (EEG signals): {X.shape}")
print(f"Shape of trial_starts (trial start samples): {trial_starts.shape}")
print(f"Shape of y (class labels): {y.shape}")
print(f"Sampling Frequency: {sampling_freq} Hz")
print(f"Class Names: {class_names}")
print(f"Unique Labels in y: {np.unique(y)}")

import numpy as np
import scipy.io
from google.colab import drive

# --- Mount Drive and Load File (if needed) ---
# drive.mount('/content/drive')
# file_path = '/content/drive/My Drive/Research-BCI/Research-BCI/archive (1)/A01T.mat'

# --- The Definitive Data Extraction ---

# 1. Load the data using the squeeze_me=True argument
mat_data_squeezed = scipy.io.loadmat(file_path, squeeze_me=True)

# 2. Access the array containing all subjects' data
all_subjects_data = mat_data_squeezed['data']

# 3. Select the data for a subject that has labels (e.g., the 4th subject at index 3)
subject_data = all_subjects_data[3] # Using Subject 4

# 4. Extract the scalar object for each field, then use .item() to get the array inside
X = subject_data['X'].item()
trial_starts = subject_data['trial'].item()
y = subject_data['y'].item()
sampling_freq = subject_data['fs'].item()
class_names = subject_data['classes'].item()

# --- Final Verification ---
print("--- Data Extraction Verified ---")
print(f"Shape of X (EEG signals): {X.shape}")
print(f"Shape of trial_starts (trial start samples): {trial_starts.shape}")
print(f"Shape of y (class labels): {y.shape}")
print(f"Number of trials: {len(y)}")
print(f"Sampling Frequency: {sampling_freq} Hz")
print(f"Class Names: {class_names}")
print(f"Unique Labels in y: {np.unique(y)}")

# --- Epoching Parameters ---
# We define the time window for each epoch in seconds
# Let's take a 4-second window starting from the stimulus onset
epoch_start_s = 0.0  # 0 seconds after the marker
epoch_end_s = 4.0    # 4 seconds after the marker

# Convert the time window into sample points
epoch_start_samples = int(epoch_start_s * sampling_freq)
epoch_end_samples = int(epoch_end_s * sampling_freq)
epoch_length_samples = epoch_end_samples - epoch_start_samples

# --- Create the Epochs ---
# We will store our epochs in a list
epochs = []

# Loop through each trial start time
for start_sample in trial_starts:
    # Define the start and end point of the slice in the X array
    start_index = start_sample + epoch_start_samples
    end_index = start_sample + epoch_end_samples

    # Slice the X array to get one epoch
    single_epoch = X[start_index:end_index, :]

    # Append the epoch to our list
    epochs.append(single_epoch)

# Convert the list of epochs into a single 3D NumPy array
# The shape will be (number_of_trials, samples_per_epoch, number_of_channels)
epochs_array = np.array(epochs)


# --- Verification ---
print("--- Epoching Complete ---")
print(f"Shape of the final epoched data (trials, samples, channels): {epochs_array.shape}")
print(f"Number of trials should match y: {len(epochs_array)}")
print(f"Number of samples per trial should be {epoch_length_samples}: {epochs_array.shape[1]}")
print(f"Number of channels should be 25: {epochs_array.shape[2]}")

# First, ensure MNE is installed if you haven't already
!pip install mne

import mne
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# --- 1. Data Splitting ---
# We split our 48 trials into a training set (e.g., 80%) and a testing set (e.g., 20%)
# The stratify=y argument ensures that the proportion of each class is the same in both sets
X_train, X_test, y_train, y_test = train_test_split(
    epochs_array, y, test_size=0.2, random_state=42, stratify=y
)

# --- 2. Band-Pass Filtering ---
# Define the frequency band of interest for motor imagery
low_freq = 8.0
high_freq = 30.0

# Apply the filter to both training and testing data
# We use the highly optimized filter from the MNE library
X_train_filtered = mne.filter.filter_data(X_train, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)
X_test_filtered = mne.filter.filter_data(X_test, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)


# --- 3. Scaling ---
# We will scale the data for each channel to have zero mean and unit variance

# The scaler needs to see a 2D array, so we reshape our 3D data
# Shape goes from (trials, samples, channels) to (trials * samples, channels)
num_train_trials, num_samples, num_channels = X_train_filtered.shape
X_train_reshaped = X_train_filtered.reshape(-1, num_channels)

num_test_trials, _, _ = X_test_filtered.shape
X_test_reshaped = X_test_filtered.reshape(-1, num_channels)

# Create and fit the scaler ONLY on the training data
scaler = StandardScaler()
scaler.fit(X_train_reshaped)

# Apply the learned scaler to both training and testing data
X_train_scaled_reshaped = scaler.transform(X_train_reshaped)
X_test_scaled_reshaped = scaler.transform(X_test_reshaped)

# Reshape the data back to its original 3D format (trials, samples, channels)
X_train_processed = X_train_scaled_reshaped.reshape(num_train_trials, num_samples, num_channels)
X_test_processed = X_test_scaled_reshaped.reshape(num_test_trials, num_samples, num_channels)


# --- Verification ---
print("--- Preprocessing Complete ---")
print(f"Shape of X_train_processed: {X_train_processed.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of X_test_processed: {X_test_processed.shape}")
print(f"Shape of y_test: {y_test.shape}")
print("\nData is now fully preprocessed and ready for the model!")

import mne
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# --- 1. Data Splitting (this was already correct) ---
X_train, X_test, y_train, y_test = train_test_split(
    epochs_array, y, test_size=0.2, random_state=42, stratify=y
)

# --- 2. Corrected Band-Pass Filtering ---
low_freq = 8.0
high_freq = 30.0

# **FIX:** Transpose the data to (trials, channels, samples) for the MNE filter
X_train_transposed = X_train.transpose(0, 2, 1)
X_test_transposed = X_test.transpose(0, 2, 1)

# Apply the filter to the transposed data
X_train_filtered = mne.filter.filter_data(X_train_transposed, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)
X_test_filtered = mne.filter.filter_data(X_test_transposed, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)

# **FIX:** Transpose the data back to (trials, samples, channels) for TensorFlow
X_train_filtered_final = X_train_filtered.transpose(0, 2, 1)
X_test_filtered_final = X_test_filtered.transpose(0, 2, 1)


# --- 3. Scaling (this was already correct, just using the correctly filtered data) ---
num_train_trials, num_samples, num_channels = X_train_filtered_final.shape
X_train_reshaped = X_train_filtered_final.reshape(-1, num_channels)

num_test_trials, _, _ = X_test_filtered_final.shape
X_test_reshaped = X_test_filtered_final.reshape(-1, num_channels)

scaler = StandardScaler()
scaler.fit(X_train_reshaped)

X_train_scaled_reshaped = scaler.transform(X_train_reshaped)
X_test_scaled_reshaped = scaler.transform(X_test_reshaped)

X_train_processed = X_train_scaled_reshaped.reshape(num_train_trials, num_samples, num_channels)
X_test_processed = X_test_scaled_reshaped.reshape(num_test_trials, num_samples, num_channels)


# --- Verification ---
print("--- Preprocessing Corrected and Complete ---")
print(f"Shape of X_train_processed: {X_train_processed.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of X_test_processed: {X_test_processed.shape}")
print(f"Shape of y_test: {y_test.shape}")
print("\nData is now correctly filtered, scaled, and ready for the model!")

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, LayerNormalization, Dropout, MultiHeadAttention, GlobalAveragePooling1D
from tensorflow.keras.models import Model

# --- Transformer Encoder Block ---
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Attention and Normalization
    x = MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x + inputs)

    # Feed Forward Part
    ffn = tf.keras.Sequential([
        Dense(ff_dim, activation="relu"),
        Dense(inputs.shape[-1]),
    ])
    x = ffn(x)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x)
    return x

# --- Build the Full Model ---
def build_transformer_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, num_classes, dropout=0):
    inputs = Input(shape=input_shape)
    x = inputs

    # Create multiple Transformer Encoder blocks
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    # Global Average Pooling to reduce the sequence to a single feature vector
    x = GlobalAveragePooling1D(data_format="channels_last")(x)

    # Final Classification Head
    x = Dropout(0.4)(x)
    x = Dense(20, activation="relu")(x)
    outputs = Dense(num_classes, activation="softmax")(x)

    return Model(inputs, outputs)

# --- Define Model Hyperparameters ---
INPUT_SHAPE = X_train_processed.shape[1:]  # (1000, 25)
NUM_CLASSES = len(np.unique(y))       # 4 classes

# Transformer-specific hyperparameters
HEAD_SIZE = 256
NUM_HEADS = 4
FF_DIM = 4  # Feed-forward network dimension
NUM_TRANSFORMER_BLOCKS = 4
DROPOUT_RATE = 0.25


# --- Create the model instance ---
model = build_transformer_model(
    INPUT_SHAPE,
    head_size=HEAD_SIZE,
    num_heads=NUM_HEADS,
    ff_dim=FF_DIM,
    num_transformer_blocks=NUM_TRANSFORMER_BLOCKS,
    num_classes=NUM_CLASSES,
    dropout=DROPOUT_RATE,
)

# Compile the model
model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    metrics=["sparse_categorical_accuracy"],
)

# --- Verification ---
# Print a summary of the model architecture
print("--- Model Architecture Summary ---")
model.summary()

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, LayerNormalization, Dropout, MultiHeadAttention, GlobalAveragePooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping # Import the EarlyStopping callback

# --- We will use the same model-building functions as before ---
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x + inputs)
    ffn = tf.keras.Sequential([Dense(ff_dim, activation="relu"), Dense(inputs.shape[-1]),])
    x = ffn(x)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x)
    return x

def build_transformer_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, num_classes, dropout=0):
    inputs = Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    x = GlobalAveragePooling1D(data_format="channels_last")(x)
    x = Dropout(0.4)(x)
    x = Dense(20, activation="relu")(x)
    outputs = Dense(num_classes, activation="softmax")(x)
    return Model(inputs, outputs)

# --- Define **UPDATED** Model Hyperparameters ---
INPUT_SHAPE = X_train_processed.shape[1:]
NUM_CLASSES = len(np.unique(y))

# **CHANGE:** Let's simplify the model to see if it learns better
NUM_TRANSFORMER_BLOCKS = 2  # Reduced from 4 to 2
HEAD_SIZE = 128             # Reduced from 256

# --- Create the **UPDATED** model instance ---
model = build_transformer_model(
    INPUT_SHAPE,
    head_size=HEAD_SIZE,
    num_heads=NUM_HEADS,
    ff_dim=FF_DIM,
    num_transformer_blocks=NUM_TRANSFORMER_BLOCKS,
    num_classes=NUM_CLASSES,
    dropout=DROPOUT_RATE,
)

# **CHANGE:** We are increasing the learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3) # Increased from 1e-4

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=optimizer,
    metrics=["sparse_categorical_accuracy"],
)

# --- Final Label Adjustment ---
y_train_adjusted = y_train - 1
y_test_adjusted = y_test - 1

# --- Define **UPDATED** Training Parameters ---
EPOCHS = 150 # Increased epochs since we have EarlyStopping
BATCH_SIZE = 8

# **NEW:** Add an EarlyStopping callback
# This will monitor the validation loss and stop the training if it doesn't improve for 15 straight epochs.
# It will also restore the weights from the best epoch.
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

# --- Train the **UPDATED** Model ---
print("--- Starting Model Training (Attempt 2) ---")
history = model.fit(
    X_train_processed,
    y_train_adjusted,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(X_test_processed, y_test_adjusted),
    callbacks=[early_stopping], # Add the callback here
    verbose=1,
)
print("\n--- Model Training Complete! ---")

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Activation, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, AveragePooling2D, BatchNormalization, DepthwiseConv2D, SeparableConv2D
from tensorflow.keras.callbacks import EarlyStopping

# --- 1. Reshape Data for EEGNet (Important!) ---
# EEGNet uses 2D convolutions, so it expects the data in a 4D format:
# (trials, channels, samples, 1)
# Our data is currently (trials, samples, channels), so we need to swap the axes and add a dimension.

X_train_eegnet = X_train_processed.transpose(0, 2, 1)
X_test_eegnet = X_test_processed.transpose(0, 2, 1)

X_train_eegnet = X_train_eegnet[..., tf.newaxis]
X_test_eegnet = X_test_eegnet[..., tf.newaxis]

print(f"Reshaped X_train for EEGNet: {X_train_eegnet.shape}")
print(f"Reshaped X_test for EEGNet: {X_test_eegnet.shape}")


# --- 2. Build the EEGNet Model ---
def EEGNet(nb_classes, Chans=25, Samples=1000, dropoutRate=0.5, kernLength=64, F1=8, D=2, F2=16):
    input1 = Input(shape=(Chans, Samples, 1))

    # Block 1
    block1 = Conv2D(F1, (1, kernLength), padding='same', use_bias=False)(input1)
    block1 = BatchNormalization()(block1)
    block1 = DepthwiseConv2D((Chans, 1), use_bias=False, depth_multiplier=D, depthwise_constraint=tf.keras.constraints.max_norm(1.))(block1)
    block1 = BatchNormalization()(block1)
    block1 = Activation('elu')(block1)
    block1 = AveragePooling2D((1, 4))(block1)
    block1 = Dropout(dropoutRate)(block1)

    # Block 2
    block2 = SeparableConv2D(F2, (1, 16), use_bias=False, padding='same')(block1)
    block2 = BatchNormalization()(block2)
    block2 = Activation('elu')(block2)
    block2 = AveragePooling2D((1, 8))(block2)
    block2 = Dropout(dropoutRate)(block2)

    # Flatten and Classify
    flatten = Flatten(name='flatten')(block2)
    dense = Dense(nb_classes, name='dense', kernel_constraint=tf.keras.constraints.max_norm(0.25))(flatten)
    softmax = Activation('softmax', name='softmax')(dense)

    return Model(inputs=input1, outputs=softmax)

# --- 3. Create and Compile the Model ---
model_eegnet = EEGNet(nb_classes=NUM_CLASSES, Chans=25, Samples=1000)

model_eegnet.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['sparse_categorical_accuracy'])
model_eegnet.summary()

# --- 4. Train the EEGNet Model ---
# Labels are already adjusted from the previous step (y_train_adjusted, y_test_adjusted)
early_stopping = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)

print("\n--- Starting EEGNet Model Training ---")
history_eegnet = model_eegnet.fit(
    X_train_eegnet,
    y_train_adjusted,
    batch_size=8,
    epochs=150,
    validation_data=(X_test_eegnet, y_test_adjusted),
    callbacks=[early_stopping],
    verbose=1
)
print("\n--- EEGNet Model Training Complete! ---")

import numpy as np
import scipy.io
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Activation, Dropout, Flatten, Conv2D, AveragePooling2D, BatchNormalization, DepthwiseConv2D, SeparableConv2D
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import mne

# --- 1. Load the data using the squeeze_me=True argument ---
mat_data_squeezed = scipy.io.loadmat(file_path, squeeze_me=True)
all_subjects_data = mat_data_squeezed['data']

# --- 2. Aggregate Data from ALL Valid Subjects ---
print("--- Aggregating data from all subjects... ---")
all_epochs = []
all_labels = []

for subject_data in all_subjects_data:
    # **FIX:** Correctly check the size of the array INSIDE the 'y' container
    if subject_data['y'].item().size > 1:
        # Extract data for this subject
        X = subject_data['X'].item()
        trial_starts = subject_data['trial'].item()
        y_subject = subject_data['y'].item() # Use a temporary variable
        sampling_freq = subject_data['fs'].item()

        # Perform epoching for this subject
        epoch_start_s = 0.0
        epoch_end_s = 4.0
        epoch_start_samples = int(epoch_start_s * sampling_freq)
        epoch_end_samples = int(epoch_end_s * sampling_freq)

        subject_epochs = []
        for start_sample in trial_starts:
            start_index = start_sample + epoch_start_samples
            end_index = start_sample + epoch_end_samples
            single_epoch = X[start_index:end_index, :]
            subject_epochs.append(single_epoch)

        all_epochs.extend(subject_epochs)
        all_labels.extend(y_subject)

# Convert lists to final NumPy arrays
epochs_array = np.array(all_epochs)
y = np.array(all_labels)

print(f"\n--- Aggregation Complete ---")
print(f"Total trials from all subjects: {len(epochs_array)}")
print(f"Shape of final epoched data: {epochs_array.shape}")
print(f"Shape of final labels: {y.shape}")


# --- 3. Preprocess the Aggregated Data (Split, Filter, Scale) ---
# (The rest of the script is the same)

# Split
X_train, X_test, y_train, y_test = train_test_split(epochs_array, y, test_size=0.2, random_state=42, stratify=y)
y_train_adjusted = y_train - 1
y_test_adjusted = y_test - 1

# Filter
low_freq = 8.0
high_freq = 30.0
X_train_transposed = X_train.transpose(0, 2, 1)
X_test_transposed = X_test.transpose(0, 2, 1)
X_train_filtered = mne.filter.filter_data(X_train_transposed, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)
X_test_filtered = mne.filter.filter_data(X_test_transposed, sfreq=sampling_freq, l_freq=low_freq, h_freq=high_freq, verbose=False)
X_train_filtered_final = X_train_filtered.transpose(0, 2, 1)
X_test_filtered_final = X_test_filtered.transpose(0, 2, 1)

# Scale
num_train_trials, num_samples, num_channels = X_train_filtered_final.shape
X_train_reshaped = X_train_filtered_final.reshape(-1, num_channels)
num_test_trials, _, _ = X_test_filtered_final.shape
X_test_reshaped = X_test_filtered_final.reshape(-1, num_channels)
scaler = StandardScaler()
scaler.fit(X_train_reshaped)
X_train_scaled_reshaped = scaler.transform(X_train_reshaped)
X_test_scaled_reshaped = scaler.transform(X_test_reshaped)
X_train_processed = X_train_scaled_reshaped.reshape(num_train_trials, num_samples, num_channels)
X_test_processed = X_test_scaled_reshaped.reshape(num_test_trials, num_samples, num_channels)

# Reshape for EEGNet
X_train_eegnet = X_train_processed.transpose(0, 2, 1)[..., tf.newaxis]
X_test_eegnet = X_test_processed.transpose(0, 2, 1)[..., tf.newaxis]

print(f"\nTotal training samples: {len(X_train_eegnet)}")
print(f"Total testing samples: {len(X_test_eegnet)}")


# --- 4. Build and Train EEGNet on the Full Dataset ---
def EEGNet(nb_classes, Chans=25, Samples=1000, dropoutRate=0.5, kernLength=64, F1=8, D=2, F2=16):
    input1 = Input(shape=(Chans, Samples, 1))
    block1 = Conv2D(F1, (1, kernLength), padding='same', use_bias=False)(input1)
    block1 = BatchNormalization()(block1)
    block1 = DepthwiseConv2D((Chans, 1), use_bias=False, depth_multiplier=D, depthwise_constraint=tf.keras.constraints.max_norm(1.))(block1)
    block1 = BatchNormalization()(block1)
    block1 = Activation('elu')(block1)
    block1 = AveragePooling2D((1, 4))(block1)
    block1 = Dropout(dropoutRate)(block1)
    block2 = SeparableConv2D(F2, (1, 16), use_bias=False, padding='same')(block1)
    block2 = BatchNormalization()(block2)
    block2 = Activation('elu')(block2)
    block2 = AveragePooling2D((1, 8))(block2)
    block2 = Dropout(dropoutRate)(block2)
    flatten = Flatten(name='flatten')(block2)
    dense = Dense(nb_classes, name='dense', kernel_constraint=tf.keras.constraints.max_norm(0.25))(flatten)
    softmax = Activation('softmax', name='softmax')(dense)
    return Model(inputs=input1, outputs=softmax)

NUM_CLASSES = len(np.unique(y))
model_eegnet_final = EEGNet(nb_classes=NUM_CLASSES, Chans=25, Samples=1000)
model_eegnet_final.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['sparse_categorical_accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)

print("\n--- Starting Final EEGNet Model Training on Full Dataset ---")
history_eegnet_final = model_eegnet_final.fit(
    X_train_eegnet,
    y_train_adjusted,
    batch_size=16,
    epochs=150,
    validation_data=(X_test_eegnet, y_test_adjusted),
    callbacks=[early_stopping],
    verbose=1
)
print("\n--- Final Model Training Complete! ---")

import joblib

# --- 1. Save the Final Trained EEGNet Model ---
# This assumes your final model variable is named 'model_eegnet_final'
model_path = '/content/drive/My Drive/eegnet_model_multisubject.h5'
model_eegnet_final.save(model_path)
print(f"Final EEGNet model saved successfully to {model_path}")


# --- 2. Save the Scaler ---
# This assumes your scaler variable from the training script is named 'scaler'
scaler_path = '/content/drive/My Drive/eeg_scaler_multisubject.joblib'
joblib.dump(scaler, scaler_path)
print(f"Scaler saved successfully to {scaler_path}")

# This code assumes you have your test data: X_test_processed and y_test_adjusted

print("--- Please copy the entire object below and paste it into your simulator.html file ---")

# Find one index for each class
left_hand_idx = np.where(y_test_adjusted == 0)[0][0]
right_hand_idx = np.where(y_test_adjusted == 1)[0][0]
feet_idx = np.where(y_test_adjusted == 2)[0][0]
tongue_idx = np.where(y_test_adjusted == 3)[0][0]

# Get the corresponding trials
# IMPORTANT: We need to use the UNFILTERED, UNSCALED test data for the demo,
# because our backend will do the preprocessing.
# This assumes your original split data is called X_test.
left_hand_trial = X_test[left_hand_idx]
right_hand_trial = X_test[right_hand_idx]
feet_trial = X_test[feet_idx]
tongue_trial = X_test[tongue_idx]

# --- COPY THE OUTPUT FROM THIS CELL ---
print("const sampleTrialData = {")
print(f'    "left_hand": {{ eeg_data: {np.array(left_hand_trial).tolist()} }},')
print(f'    "right_hand": {{ eeg_data: {np.array(right_hand_trial).tolist()} }},')
print(f'    "feet": {{ eeg_data: {np.array(feet_trial).tolist()} }},')
print(f'    "tongue": {{ eeg_data: {np.array(tongue_trial).tolist()} }}')
print("};")

from pyngrok import ngrok

# --- Set Up Your ngrok Authtoken ---
# Paste the authtoken you copied from the ngrok dashboard here
AUTHTOKEN = "32BzsC4KkvuS3Und1QpkUZjbOs4_5Ts6PW3PJLi8n5K289SAR"

ngrok.set_auth_token(AUTHTOKEN)

print("ngrok authtoken configured successfully!")

# --- 1. Install necessary libraries ---
!pip install flask pyngrok joblib flask-cors

# --- 2. Import all required modules ---
import joblib
import numpy as np
import tensorflow as tf
from flask import Flask, request, jsonify
from pyngrok import ngrok
from flask_cors import CORS  # Import CORS
import mne

# --- 3. Load the trained model and the saved scaler ---
print("Loading model and scaler...")
model_path = '/content/drive/My Drive/eegnet_model_multisubject.h5'
scaler_path = '/content/drive/My Drive/eeg_scaler_multisubject.joblib'
model = tf.keras.models.load_model(model_path)
scaler = joblib.load(scaler_path)
print("Model and scaler loaded successfully!")

# Define constants
SAMPLING_FREQ = 250
CLASS_NAMES = ['left hand', 'right hand', 'feet', 'tongue']

# --- 4. Define the preprocessing function ---
def preprocess_single_trial(eeg_data):
    eeg_transposed = eeg_data.transpose(1, 0)
    eeg_filtered = mne.filter.filter_data(eeg_transposed, sfreq=SAMPLING_FREQ,
                                          l_freq=8.0, h_freq=30.0, verbose=False)
    eeg_filtered_final = eeg_filtered.transpose(1, 0)
    eeg_scaled = scaler.transform(eeg_filtered_final)
    eeg_reshaped = eeg_scaled.transpose(1, 0)
    eeg_final = eeg_reshaped[np.newaxis, ..., np.newaxis]
    return eeg_final

# --- 5. Create the Flask Web Server ---
app = Flask(__name__)
CORS(app)

@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({'status': 'ok'})

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    eeg_trial_raw = np.array(data['eeg_data'])

    # --- THE DEFINITIVE FIX ---
    # We forcefully reshape the incoming data into the (1000, 25) 2D array
    # that our preprocessing function requires.
    try:
        eeg_trial_2d = eeg_trial_raw.reshape(1000, 25)
    except ValueError:
        # If reshape fails, it means the data is completely wrong.
        # We'll send back an error to the UI.
        return jsonify({'error': 'Incoming data did not have the correct number of elements (25000).'}), 400

    # Now we pass the correctly shaped 2D array to the preprocessor
    processed_trial = preprocess_single_trial(eeg_trial_2d)

    prediction_probabilities = model.predict(processed_trial)[0]

    predicted_class_index = np.argmax(prediction_probabilities)
    predicted_class_name = CLASS_NAMES[predicted_class_index]
    confidence_score = float(prediction_probabilities[predicted_class_index])

    return jsonify({
        'prediction': predicted_class_name,
        'confidence': confidence_score
    })



# --- 6. Start the server using ngrok ---
# Configure your ngrok authtoken if you haven't already
# AUTHTOKEN = "32BzsC4KkvuS3Und1QpkUZjbOs4_5Ts6PW3PJLi8n5K289SAR"
# ngrok.set_auth_token(AUTHTOKEN)

print("\nStarting ngrok tunnel...")
public_url = ngrok.connect(5000)
print("------------------------------------------------------------------")
print(f"COPY THIS PUBLIC URL: {public_url}")
print("------------------------------------------------------------------")
print("Starting Flask server... (This will run until you manually stop it)")

app.run(port=5000)

!pip install mne

import numpy as np
import random
import time

# --- IMPORTANT ---
# Run this script in the *same environment* (e.g., your Google Colab notebook)
# where your `X_test_processed` and `y_test_adjusted` variables are loaded.
# This script will NOT work on its own as it depends on your data.

def generate_new_sample_block():
    """
    Finds a new random trial for each class and prints the
    JavaScript object.
    """

    # 1. Check if the required data exists in the environment
    if 'X_test_processed' not in locals() or 'y_test_adjusted' not in locals():
        print("ERROR: `X_test_processed` and `y_test_adjusted` are not defined.")
        print("Please run this script in the environment where your data is loaded.")
        return False # Stop the script

    # 2. Find ALL indices for each class
    try:
        left_hand_indices = np.where(y_test_adjusted == 0)[0]
        right_hand_indices = np.where(y_test_adjusted == 1)[0]
        feet_indices = np.where(y_test_adjusted == 2)[0]
        tongue_indices = np.where(y_test_adjusted == 3)[0]

        if any(len(idx_list) == 0 for idx_list in [left_hand_indices, right_hand_indices, feet_indices, tongue_indices]):
            print("ERROR: One or more classes have no samples in `y_test_adjusted`.")
            return False

    except Exception as e:
        print(f"An error occurred while finding indices: {e}")
        print("Make sure `y_test_adjusted` is a numpy array with values 0, 1, 2, 3.")
        return False

    # 3. Pick one RANDOM index from each list
    left_hand_idx = random.choice(left_hand_indices)
    right_hand_idx = random.choice(right_hand_indices)
    feet_idx = random.choice(feet_indices)
    tongue_idx = random.choice(tongue_indices)

    # 4. Get the corresponding trials from your dataset
    left_hand_trial = X_test_processed[left_hand_idx]
    right_hand_trial = X_test_processed[right_hand_idx]
    feet_trial = X_test_processed[feet_idx]
    tongue_trial = X_test_processed[tongue_idx]

    # 5. Print the formatted block
    print("const sampleTrials = {")
    print(f'    "left hand": {np.array(left_hand_trial).tolist()},')
    print(f'    "right hand": {np.array(right_hand_trial).tolist()},')
    print(f'    "feet": {np.array(feet_trial).tolist()},')
    print(f'    "tongue": {np.array(tongue_trial).tolist()}')
    print("};")

    return True

if __name__ == "__main__":
    print("Starting continuous sample trial generation...")
    print("Press Ctrl+C to stop.")
    print("----------------------------------------------")

    # Set the delay between generating new blocks (in seconds)
    GENERATION_INTERVAL = 5

    try:
        while True:
            if not generate_new_sample_block():
                # Stop if data wasn't found
                break

            print("\n--- NEW SAMPLE BLOCK GENERATED ---")
            print(f"Waiting {GENERATION_INTERVAL} seconds...\n")
            time.sleep(GENERATION_INTERVAL)

    except KeyboardInterrupt:
        print("\nStopping generator.")

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, LayerNormalization, Dropout, MultiHeadAttention, GlobalAveragePooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

# Note: This code assumes you have the variables from the previous step:
# X_train_processed, y_train_adjusted, X_test_processed, y_test_adjusted

# --- 1. Build the Transformer Model (using the simplified version from our last attempt) ---
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    x = MultiHeadAttention(key_dim=head_size, num_heads=num_heads, dropout=dropout)(inputs, inputs)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x + inputs)
    ffn = tf.keras.Sequential([Dense(ff_dim, activation="relu"), Dense(inputs.shape[-1]),])
    x = ffn(x)
    x = Dropout(dropout)(x)
    x = LayerNormalization(epsilon=1e-6)(x)
    return x

def build_transformer_model(input_shape, head_size, num_heads, ff_dim, num_transformer_blocks, num_classes, dropout=0):
    inputs = Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    x = GlobalAveragePooling1D(data_format="channels_last")(x)
    x = Dropout(0.4)(x)
    x = Dense(20, activation="relu")(x)
    outputs = Dense(num_classes, activation="softmax")(x)
    return Model(inputs, outputs)

# --- 2. Define Model Hyperparameters ---
INPUT_SHAPE = X_train_processed.shape[1:]
NUM_CLASSES = len(np.unique(y))
NUM_TRANSFORMER_BLOCKS = 2
HEAD_SIZE = 128
NUM_HEADS = 4
FF_DIM = 4
DROPOUT_RATE = 0.25

# --- 3. Create and Compile the Model ---
model_transformer = build_transformer_model(
    INPUT_SHAPE,
    head_size=HEAD_SIZE,
    num_heads=NUM_HEADS,
    ff_dim=FF_DIM,
    num_transformer_blocks=NUM_TRANSFORMER_BLOCKS,
    num_classes=NUM_CLASSES,
    dropout=DROPOUT_RATE,
)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
model_transformer.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=optimizer,
    metrics=["sparse_categorical_accuracy"],
)
model_transformer.summary()


# --- 4. Train the Transformer on the Full Dataset ---
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

print("\n--- Starting Transformer Model Training on Full Dataset ---")
history_transformer = model_transformer.fit(
    X_train_processed,
    y_train_adjusted,
    batch_size=16,
    epochs=150,
    validation_data=(X_test_processed, y_test_adjusted),
    callbacks=[early_stopping],
    verbose=1
)
print("\n--- Transformer Model Training Complete! ---")


# --- 5. Final Evaluation ---
print("\n--- Final Transformer Model Evaluation ---")
final_loss_transformer, final_accuracy_transformer = model_transformer.evaluate(X_test_processed, y_test_adjusted, verbose=0)
print(f"Final Test Loss: {final_loss_transformer:.4f}")
print(f"Final Test Accuracy: {final_accuracy_transformer:.4f} ({(final_accuracy_transformer * 100):.2f}%)")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# --- 1. Evaluate the Final Model on the Test Set ---
print("--- Final Model Evaluation ---")
final_loss, final_accuracy = model_eegnet_final.evaluate(X_test_eegnet, y_test_adjusted, verbose=0)
print(f"Final Test Loss: {final_loss:.4f}")
print(f"Final Test Accuracy: {final_accuracy:.4f} ({(final_accuracy * 100):.2f}%)")


# --- 2. Plot Training and Validation History ---
print("\n--- Plotting Training History ---")
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history_eegnet_final.history['sparse_categorical_accuracy'], label='Training Accuracy')
plt.plot(history_eegnet_final.history['val_sparse_categorical_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(history_eegnet_final.history['loss'], label='Training Loss')
plt.plot(history_eegnet_final.history['val_loss'], label='Validation Loss')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()


# --- 3. Generate Classification Report and Confusion Matrix ---
print("\n--- Classification Report and Confusion Matrix ---")
y_pred = model_eegnet_final.predict(X_test_eegnet)
y_pred_classes = np.argmax(y_pred, axis=1)
class_names = ['left hand', 'right hand', 'feet', 'tongue']
print("\nClassification Report:")
print(classification_report(y_test_adjusted, y_pred_classes, target_names=class_names))
cm = confusion_matrix(y_test_adjusted, y_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, BatchNormalization
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# Note: This code assumes you have the variables from the aggregation step:
# X_train_processed, y_train_adjusted, X_test_processed, y_test_adjusted

print("--- Data Shapes for CNN-LSTM ---")
print(f"X_train_processed shape: {X_train_processed.shape}")
print(f"X_test_processed shape: {X_test_processed.shape}")


# --- 1. Build the CNN-LSTM Model ---
def build_cnnlstm_model(input_shape, num_classes):
    inputs = Input(shape=input_shape)

    # CNN Block
    x = Conv1D(filters=64, kernel_size=16, activation='relu')(inputs)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.5)(x)

    x = Conv1D(filters=64, kernel_size=16, activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.5)(x)

    # LSTM Block
    x = LSTM(128, return_sequences=False)(x) # return_sequences=False because it's the last LSTM
    x = Dropout(0.5)(x)

    # Classification Head
    outputs = Dense(num_classes, activation='softmax')(x)

    return Model(inputs, outputs)

# --- 2. Create and Compile the Model ---
INPUT_SHAPE = X_train_processed.shape[1:] # (1000, 25)
NUM_CLASSES = len(np.unique(y))       # 4 classes

model_cnnlstm = build_cnnlstm_model(INPUT_SHAPE, NUM_CLASSES)
model_cnnlstm.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['sparse_categorical_accuracy'])
model_cnnlstm.summary()


# --- 3. Train the CNN-LSTM Model ---
early_stopping = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)

print("\n--- Starting CNN-LSTM Model Training ---")
history_cnnlstm = model_cnnlstm.fit(
    X_train_processed,
    y_train_adjusted,
    batch_size=16,
    epochs=150,
    validation_data=(X_test_processed, y_test_adjusted),
    callbacks=[early_stopping],
    verbose=1
)
print("\n--- CNN-LSTM Model Training Complete! ---")


# --- 4. Final Evaluation ---
print("\n--- Final CNN-LSTM Model Evaluation ---")
final_loss_cnnlstm, final_accuracy_cnnlstm = model_cnnlstm.evaluate(X_test_processed, y_test_adjusted, verbose=0)
print(f"Final Test Loss: {final_loss_cnnlstm:.4f}")
print(f"Final Test Accuracy: {final_accuracy_cnnlstm:.4f} ({(final_accuracy_cnnlstm * 100):.2f}%)")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# --- 1. Plot Training and Validation History for CNN-LSTM ---
print("\n--- Plotting CNN-LSTM Training History ---")
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history_cnnlstm.history['sparse_categorical_accuracy'], label='Training Accuracy')
plt.plot(history_cnnlstm.history['val_sparse_categorical_accuracy'], label='Validation Accuracy')
plt.title('CNN-LSTM Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(history_cnnlstm.history['loss'], label='Training Loss')
plt.plot(history_cnnlstm.history['val_loss'], label='Validation Loss')
plt.title('CNN-LSTM Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.tight_layout()
plt.show()


# --- 2. Generate Classification Report and Confusion Matrix for CNN-LSTM ---
print("\n--- CNN-LSTM Classification Report and Confusion Matrix ---")
y_pred = model_cnnlstm.predict(X_test_processed)
y_pred_classes = np.argmax(y_pred, axis=1)
class_names = ['left hand', 'right hand', 'feet', 'tongue']
print("\nClassification Report:")
print(classification_report(y_test_adjusted, y_pred_classes, target_names=class_names))
cm = confusion_matrix(y_test_adjusted, y_pred_classes)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('CNN-LSTM Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# --- Final CNN-LSTM Model Evaluation ---
print("\n--- Final CNN-LSTM Model Evaluation ---")

# This assumes your trained CNN-LSTM model is named 'model_cnnlstm'
# and your test data is 'X_test_processed' and 'y_test_adjusted'
final_loss_cnnlstm, final_accuracy_cnnlstm = model_cnnlstm.evaluate(X_test_processed, y_test_adjusted, verbose=0)

print(f"Final Test Loss: {final_loss_cnnlstm:.4f}")
print(f"Final Test Accuracy: {final_accuracy_cnnlstm:.4f} ({(final_accuracy_cnnlstm * 100):.2f}%)")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# --- 1. Define the Data ---
# These are the final, definitive test accuracies we achieved for each model.
model_names = ['Transformer', 'CNN-LSTM', 'EEGNet']
accuracies = [25.86, 56.90, 68.97]

# --- 2. Create the Plot ---
# Set a professional style for the plot
sns.set_style("whitegrid")
plt.figure(figsize=(10, 6))

# Create the bar plot
bar_plot = sns.barplot(x=model_names, y=accuracies, palette="viridis")

# --- 3. Add Labels and Title ---
plt.xlabel("Model Architecture", fontsize=14)
plt.ylabel("Final Test Accuracy (%)", fontsize=14)
plt.title("Comparative Performance of Deep Learning Architectures", fontsize=16, weight='bold')
plt.ylim(0, 100) # Set the y-axis to go from 0 to 100 for percentage context

# --- 4. Add Data Labels on Top of Each Bar ---
# This loop goes through each bar and places the accuracy value on top of it
for index, value in enumerate(accuracies):
    plt.text(index, value + 1, f"{value:.2f}%", ha='center', va='bottom', fontsize=12)

# --- 5. Display the Plot ---
plt.show()

import joblib

# Define the path to save the scaler in your Google Drive
scaler_path = '/content/drive/My Drive/eeg_scaler.joblib'

# Save the scaler object
# This assumes your scaler variable from the training script is named 'scaler'
joblib.dump(scaler, scaler_path)

print(f"Scaler saved successfully to {scaler_path}")